DJANGO_APP_URL_CONFIG = (
    f"from django.urls import path\n"
    f"from views import hello\n\n"
    f"urlpatterns = [\n"
    f"    path('', hello, name='hello'),\n"
    f"]\n"
)

DJANGO_VIEW_FUNCTION_IMPORT_JSON_RESPONSE = "from django.http import JsonResponse\n\n"

DJANGO_VIEW_FUNCTION_MESSAGE = '{"success": True, "message": "hello"}'

DJANGO_VIEW_FUNCTION = (
    f"def hello() -> JsonResponse:\n"
    f"  return JsonResponse({DJANGO_VIEW_FUNCTION_MESSAGE})"
)

DJANGO_DRF_SETTINGS = (
    "\n\nREST_FRAMEWORK = {\n"
    "    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',\n"
    "    'PAGE_SIZE': 10,\n"
    "}\n"
)

DJANGO_DRF_SERIALIZER = (
    "from rest_framework import serializers\n\n\n"
    "class HelloSerializer(serializers.Serializer):\n"
    "    message = serializers.CharField(max_length=200)\n"
)

DJANGO_DRF_VIEW = (
    "from rest_framework.views import APIView\n"
    "from rest_framework.response import Response\n"
    "from rest_framework import status\n"
    "from .serializers import HelloSerializer\n\n\n"
    "class HelloView(APIView):\n"
    "    def get(self, request):\n"
    "        data = {'message': 'hello'}\n"
    "        serializer = HelloSerializer(data)\n"
    "        return Response(serializer.data, status=status.HTTP_200_OK)\n"
)

DJANGO_DRF_URL_CONFIG = (
    "from django.urls import path\n"
    "from .views import HelloView\n\n"
    "urlpatterns = [\n"
    "    path('', HelloView.as_view(), name='hello'),\n"
    "]\n"
)

DJANGO_POSTGRESQL_DATABASES = (
    "DATABASES = {\n"
    "    'default': {\n"
    "        'ENGINE': 'django.db.backends.postgresql',\n"
    "        'NAME': os.environ.get('DB_NAME', 'mydb'),\n"
    "        'USER': os.environ.get('DB_USER', 'postgres'),\n"
    "        'PASSWORD': os.environ.get('DB_PASSWORD', ''),\n"
    "        'HOST': os.environ.get('DB_HOST', 'localhost'),\n"
    "        'PORT': os.environ.get('DB_PORT', '5432'),\n"
    "    }\n"
    "}\n"
)

DJANGO_POSTGRESQL_ENV_EXAMPLE = (
    "DB_NAME=mydb\n"
    "DB_USER=postgres\n"
    "DB_PASSWORD=\n"
    "DB_HOST=localhost\n"
    "DB_PORT=5432\n"
)

DJANGO_CUSTOM_AUTH_MODEL = (
    "from django.contrib.auth.models import AbstractUser\n"
    "from django.db import models\n\n\n"
    "class User(AbstractUser):\n"
    "    \"\"\"Custom user model. Add extra fields here.\"\"\"\n"
    "    pass\n"
)

DJANGO_CUSTOM_AUTH_ADMIN = (
    "from django.contrib import admin\n"
    "from django.contrib.auth.admin import UserAdmin\n"
    "from .models import User\n\n\n"
    "@admin.register(User)\n"
    "class CustomUserAdmin(UserAdmin):\n"
    "    pass\n"
)

DJANGO_CUSTOM_AUTH_FORMS = (
    "from django.contrib.auth.forms import UserCreationForm, UserChangeForm\n"
    "from .models import User\n\n\n"
    "class CustomUserCreationForm(UserCreationForm):\n"
    "    class Meta(UserCreationForm.Meta):\n"
    "        model = User\n\n\n"
    "class CustomUserChangeForm(UserChangeForm):\n"
    "    class Meta(UserChangeForm.Meta):\n"
    "        model = User\n"
)

DJANGO_CUSTOM_AUTH_CBV_VIEWS = (
    "import json\n"
    "from django.contrib.auth import authenticate, login, logout\n"
    "from django.contrib.auth.decorators import login_required\n"
    "from django.contrib.auth.tokens import default_token_generator\n"
    "from django.http import JsonResponse\n"
    "from django.utils.decorators import method_decorator\n"
    "from django.utils.encoding import force_bytes, force_str\n"
    "from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode\n"
    "from django.views import View\n"
    "from django.views.decorators.csrf import csrf_exempt\n"
    "from .models import User\n\n\n"
    "@method_decorator(csrf_exempt, name='dispatch')\n"
    "class RegisterView(View):\n"
    "    def post(self, request):\n"
    "        data = json.loads(request.body)\n"
    "        username = data.get('username')\n"
    "        password = data.get('password')\n"
    "        email = data.get('email', '')\n"
    "        if not username or not password:\n"
    "            return JsonResponse({'error': 'username and password required'}, status=400)\n"
    "        if User.objects.filter(username=username).exists():\n"
    "            return JsonResponse({'error': 'username already taken'}, status=400)\n"
    "        user = User.objects.create_user(username=username, password=password, email=email)\n"
    "        return JsonResponse({'id': user.id, 'username': user.username}, status=201)\n\n\n"
    "@method_decorator(csrf_exempt, name='dispatch')\n"
    "class LoginView(View):\n"
    "    def post(self, request):\n"
    "        data = json.loads(request.body)\n"
    "        user = authenticate(request, username=data.get('username'), password=data.get('password'))\n"
    "        if user is None:\n"
    "            return JsonResponse({'error': 'invalid credentials'}, status=401)\n"
    "        login(request, user)\n"
    "        return JsonResponse({'id': user.id, 'username': user.username})\n\n\n"
    "@method_decorator(csrf_exempt, name='dispatch')\n"
    "class LogoutView(View):\n"
    "    def post(self, request):\n"
    "        logout(request)\n"
    "        return JsonResponse({'message': 'logged out'})\n\n\n"
    "@method_decorator([csrf_exempt, login_required], name='dispatch')\n"
    "class ProfileView(View):\n"
    "    def get(self, request):\n"
    "        user = request.user\n"
    "        return JsonResponse({'id': user.id, 'username': user.username, 'email': user.email})\n\n"
    "    def put(self, request):\n"
    "        data = json.loads(request.body)\n"
    "        user = request.user\n"
    "        user.email = data.get('email', user.email)\n"
    "        user.save()\n"
    "        return JsonResponse({'id': user.id, 'username': user.username, 'email': user.email})\n\n\n"
    "@method_decorator(csrf_exempt, name='dispatch')\n"
    "class ForgotPasswordView(View):\n"
    "    def post(self, request):\n"
    "        email = json.loads(request.body).get('email', '')\n"
    "        for user in User.objects.filter(email=email):\n"
    "            uid = urlsafe_base64_encode(force_bytes(user.pk))\n"
    "            token = default_token_generator.make_token(user)\n"
    "            # TODO: send email with uid and token in production\n"
    "            return JsonResponse({'uid': uid, 'token': token})\n"
    "        return JsonResponse({'message': 'if the email exists a reset link has been sent'})\n\n\n"
    "@method_decorator(csrf_exempt, name='dispatch')\n"
    "class ResetPasswordView(View):\n"
    "    def post(self, request):\n"
    "        data = json.loads(request.body)\n"
    "        try:\n"
    "            pk = force_str(urlsafe_base64_decode(data.get('uid', '')))\n"
    "            user = User.objects.get(pk=pk)\n"
    "        except (User.DoesNotExist, ValueError, TypeError):\n"
    "            return JsonResponse({'error': 'invalid link'}, status=400)\n"
    "        if not default_token_generator.check_token(user, data.get('token', '')):\n"
    "            return JsonResponse({'error': 'invalid or expired token'}, status=400)\n"
    "        user.set_password(data.get('new_password', ''))\n"
    "        user.save()\n"
    "        return JsonResponse({'message': 'password reset successfully'})\n"
)

DJANGO_CUSTOM_AUTH_CBV_URL_CONFIG = (
    "from django.urls import path\n"
    "from .views import RegisterView, LoginView, LogoutView, ProfileView, ForgotPasswordView, ResetPasswordView\n\n"
    "urlpatterns = [\n"
    "    path('register/', RegisterView.as_view(), name='register'),\n"
    "    path('login/', LoginView.as_view(), name='login'),\n"
    "    path('logout/', LogoutView.as_view(), name='logout'),\n"
    "    path('profile/', ProfileView.as_view(), name='profile'),\n"
    "    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),\n"
    "    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),\n"
    "]\n"
)

DJANGO_CUSTOM_AUTH_FBV_VIEWS = (
    "import json\n"
    "from django.contrib.auth import authenticate, login, logout\n"
    "from django.contrib.auth.decorators import login_required\n"
    "from django.contrib.auth.tokens import default_token_generator\n"
    "from django.http import JsonResponse\n"
    "from django.utils.encoding import force_bytes, force_str\n"
    "from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode\n"
    "from django.views.decorators.csrf import csrf_exempt\n"
    "from django.views.decorators.http import require_POST, require_http_methods\n"
    "from .models import User\n\n\n"
    "@csrf_exempt\n"
    "@require_POST\n"
    "def register(request):\n"
    "    data = json.loads(request.body)\n"
    "    username = data.get('username')\n"
    "    password = data.get('password')\n"
    "    email = data.get('email', '')\n"
    "    if not username or not password:\n"
    "        return JsonResponse({'error': 'username and password required'}, status=400)\n"
    "    if User.objects.filter(username=username).exists():\n"
    "        return JsonResponse({'error': 'username already taken'}, status=400)\n"
    "    user = User.objects.create_user(username=username, password=password, email=email)\n"
    "    return JsonResponse({'id': user.id, 'username': user.username}, status=201)\n\n\n"
    "@csrf_exempt\n"
    "@require_POST\n"
    "def login_view(request):\n"
    "    data = json.loads(request.body)\n"
    "    user = authenticate(request, username=data.get('username'), password=data.get('password'))\n"
    "    if user is None:\n"
    "        return JsonResponse({'error': 'invalid credentials'}, status=401)\n"
    "    login(request, user)\n"
    "    return JsonResponse({'id': user.id, 'username': user.username})\n\n\n"
    "@csrf_exempt\n"
    "@require_POST\n"
    "def logout_view(request):\n"
    "    logout(request)\n"
    "    return JsonResponse({'message': 'logged out'})\n\n\n"
    "@csrf_exempt\n"
    "@login_required\n"
    "@require_http_methods(['GET', 'PUT'])\n"
    "def profile(request):\n"
    "    user = request.user\n"
    "    if request.method == 'GET':\n"
    "        return JsonResponse({'id': user.id, 'username': user.username, 'email': user.email})\n"
    "    data = json.loads(request.body)\n"
    "    user.email = data.get('email', user.email)\n"
    "    user.save()\n"
    "    return JsonResponse({'id': user.id, 'username': user.username, 'email': user.email})\n\n\n"
    "@csrf_exempt\n"
    "@require_POST\n"
    "def forgot_password(request):\n"
    "    email = json.loads(request.body).get('email', '')\n"
    "    for user in User.objects.filter(email=email):\n"
    "        uid = urlsafe_base64_encode(force_bytes(user.pk))\n"
    "        token = default_token_generator.make_token(user)\n"
    "        # TODO: send email with uid and token in production\n"
    "        return JsonResponse({'uid': uid, 'token': token})\n"
    "    return JsonResponse({'message': 'if the email exists a reset link has been sent'})\n\n\n"
    "@csrf_exempt\n"
    "@require_POST\n"
    "def reset_password(request):\n"
    "    data = json.loads(request.body)\n"
    "    try:\n"
    "        pk = force_str(urlsafe_base64_decode(data.get('uid', '')))\n"
    "        user = User.objects.get(pk=pk)\n"
    "    except (User.DoesNotExist, ValueError, TypeError):\n"
    "        return JsonResponse({'error': 'invalid link'}, status=400)\n"
    "    if not default_token_generator.check_token(user, data.get('token', '')):\n"
    "        return JsonResponse({'error': 'invalid or expired token'}, status=400)\n"
    "    user.set_password(data.get('new_password', ''))\n"
    "    user.save()\n"
    "    return JsonResponse({'message': 'password reset successfully'})\n"
)

DJANGO_CUSTOM_AUTH_FBV_URL_CONFIG = (
    "from django.urls import path\n"
    "from .views import register, login_view, logout_view, profile, forgot_password, reset_password\n\n"
    "urlpatterns = [\n"
    "    path('register/', register, name='register'),\n"
    "    path('login/', login_view, name='login'),\n"
    "    path('logout/', logout_view, name='logout'),\n"
    "    path('profile/', profile, name='profile'),\n"
    "    path('forgot-password/', forgot_password, name='forgot-password'),\n"
    "    path('reset-password/', reset_password, name='reset-password'),\n"
    "]\n"
)

DJANGO_JWT_DRF_SETTINGS = (
    "\n\nfrom datetime import timedelta\n"
    "\nREST_FRAMEWORK = {\n"
    "    'DEFAULT_AUTHENTICATION_CLASSES': [\n"
    "        'rest_framework_simplejwt.authentication.JWTAuthentication',\n"
    "    ],\n"
    "    'DEFAULT_PERMISSION_CLASSES': [\n"
    "        'rest_framework.permissions.IsAuthenticated',\n"
    "    ],\n"
    "}\n"
    "\nSIMPLE_JWT = {\n"
    "    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),\n"
    "    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),\n"
    "    'ROTATE_REFRESH_TOKENS': True,\n"
    "    'BLACKLIST_AFTER_ROTATION': True,\n"
    "    'AUTH_HEADER_TYPES': ('Bearer',),\n"
    "}\n"
)

DJANGO_JWT_CBV_VIEWS = (
    "from django.contrib.auth import authenticate\n"
    "from django.contrib.auth.tokens import default_token_generator\n"
    "from django.utils.encoding import force_bytes, force_str\n"
    "from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode\n"
    "from rest_framework import status\n"
    "from rest_framework.permissions import AllowAny, IsAuthenticated\n"
    "from rest_framework.response import Response\n"
    "from rest_framework.views import APIView\n"
    "from rest_framework_simplejwt.tokens import RefreshToken\n"
    "from .models import User\n\n\n"
    "class RegisterView(APIView):\n"
    "    permission_classes = [AllowAny]\n\n"
    "    def post(self, request):\n"
    "        username = request.data.get('username')\n"
    "        password = request.data.get('password')\n"
    "        email = request.data.get('email', '')\n"
    "        if not username or not password:\n"
    "            return Response({'error': 'username and password required'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "        if User.objects.filter(username=username).exists():\n"
    "            return Response({'error': 'username already taken'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "        user = User.objects.create_user(username=username, password=password, email=email)\n"
    "        refresh = RefreshToken.for_user(user)\n"
    "        return Response({\n"
    "            'id': user.id, 'username': user.username,\n"
    "            'access': str(refresh.access_token), 'refresh': str(refresh),\n"
    "        }, status=status.HTTP_201_CREATED)\n\n\n"
    "class LoginView(APIView):\n"
    "    permission_classes = [AllowAny]\n\n"
    "    def post(self, request):\n"
    "        user = authenticate(request, username=request.data.get('username'), password=request.data.get('password'))\n"
    "        if user is None:\n"
    "            return Response({'error': 'invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)\n"
    "        refresh = RefreshToken.for_user(user)\n"
    "        return Response({'access': str(refresh.access_token), 'refresh': str(refresh)})\n\n\n"
    "class LogoutView(APIView):\n"
    "    permission_classes = [IsAuthenticated]\n\n"
    "    def post(self, request):\n"
    "        try:\n"
    "            RefreshToken(request.data.get('refresh')).blacklist()\n"
    "        except Exception:\n"
    "            pass\n"
    "        return Response({'message': 'logged out'})\n\n\n"
    "class ProfileView(APIView):\n"
    "    permission_classes = [IsAuthenticated]\n\n"
    "    def get(self, request):\n"
    "        user = request.user\n"
    "        return Response({'id': user.id, 'username': user.username, 'email': user.email})\n\n"
    "    def put(self, request):\n"
    "        user = request.user\n"
    "        user.email = request.data.get('email', user.email)\n"
    "        user.save()\n"
    "        return Response({'id': user.id, 'username': user.username, 'email': user.email})\n\n\n"
    "class ForgotPasswordView(APIView):\n"
    "    permission_classes = [AllowAny]\n\n"
    "    def post(self, request):\n"
    "        email = request.data.get('email', '')\n"
    "        for user in User.objects.filter(email=email):\n"
    "            uid = urlsafe_base64_encode(force_bytes(user.pk))\n"
    "            token = default_token_generator.make_token(user)\n"
    "            # TODO: send email with uid and token in production\n"
    "            return Response({'uid': uid, 'token': token})\n"
    "        return Response({'message': 'if the email exists a reset link has been sent'})\n\n\n"
    "class ResetPasswordView(APIView):\n"
    "    permission_classes = [AllowAny]\n\n"
    "    def post(self, request):\n"
    "        try:\n"
    "            pk = force_str(urlsafe_base64_decode(request.data.get('uid', '')))\n"
    "            user = User.objects.get(pk=pk)\n"
    "        except (User.DoesNotExist, ValueError, TypeError):\n"
    "            return Response({'error': 'invalid link'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "        if not default_token_generator.check_token(user, request.data.get('token', '')):\n"
    "            return Response({'error': 'invalid or expired token'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "        user.set_password(request.data.get('new_password', ''))\n"
    "        user.save()\n"
    "        return Response({'message': 'password reset successfully'})\n"
)

DJANGO_JWT_CBV_URL_CONFIG = (
    "from django.urls import path\n"
    "from rest_framework_simplejwt.views import TokenRefreshView\n"
    "from .views import RegisterView, LoginView, LogoutView, ProfileView, ForgotPasswordView, ResetPasswordView\n\n"
    "urlpatterns = [\n"
    "    path('register/', RegisterView.as_view(), name='register'),\n"
    "    path('login/', LoginView.as_view(), name='login'),\n"
    "    path('logout/', LogoutView.as_view(), name='logout'),\n"
    "    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),\n"
    "    path('profile/', ProfileView.as_view(), name='profile'),\n"
    "    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),\n"
    "    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),\n"
    "]\n"
)

DJANGO_JWT_FBV_VIEWS = (
    "from django.contrib.auth import authenticate\n"
    "from django.contrib.auth.tokens import default_token_generator\n"
    "from django.utils.encoding import force_bytes, force_str\n"
    "from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode\n"
    "from rest_framework import status\n"
    "from rest_framework.decorators import api_view, permission_classes\n"
    "from rest_framework.permissions import AllowAny, IsAuthenticated\n"
    "from rest_framework.response import Response\n"
    "from rest_framework_simplejwt.tokens import RefreshToken\n"
    "from .models import User\n\n\n"
    "@api_view(['POST'])\n"
    "@permission_classes([AllowAny])\n"
    "def register(request):\n"
    "    username = request.data.get('username')\n"
    "    password = request.data.get('password')\n"
    "    email = request.data.get('email', '')\n"
    "    if not username or not password:\n"
    "        return Response({'error': 'username and password required'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "    if User.objects.filter(username=username).exists():\n"
    "        return Response({'error': 'username already taken'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "    user = User.objects.create_user(username=username, password=password, email=email)\n"
    "    refresh = RefreshToken.for_user(user)\n"
    "    return Response({\n"
    "        'id': user.id, 'username': user.username,\n"
    "        'access': str(refresh.access_token), 'refresh': str(refresh),\n"
    "    }, status=status.HTTP_201_CREATED)\n\n\n"
    "@api_view(['POST'])\n"
    "@permission_classes([AllowAny])\n"
    "def login_view(request):\n"
    "    user = authenticate(request, username=request.data.get('username'), password=request.data.get('password'))\n"
    "    if user is None:\n"
    "        return Response({'error': 'invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)\n"
    "    refresh = RefreshToken.for_user(user)\n"
    "    return Response({'access': str(refresh.access_token), 'refresh': str(refresh)})\n\n\n"
    "@api_view(['POST'])\n"
    "@permission_classes([IsAuthenticated])\n"
    "def logout_view(request):\n"
    "    try:\n"
    "        RefreshToken(request.data.get('refresh')).blacklist()\n"
    "    except Exception:\n"
    "        pass\n"
    "    return Response({'message': 'logged out'})\n\n\n"
    "@api_view(['GET', 'PUT'])\n"
    "@permission_classes([IsAuthenticated])\n"
    "def profile(request):\n"
    "    user = request.user\n"
    "    if request.method == 'GET':\n"
    "        return Response({'id': user.id, 'username': user.username, 'email': user.email})\n"
    "    user.email = request.data.get('email', user.email)\n"
    "    user.save()\n"
    "    return Response({'id': user.id, 'username': user.username, 'email': user.email})\n\n\n"
    "@api_view(['POST'])\n"
    "@permission_classes([AllowAny])\n"
    "def forgot_password(request):\n"
    "    email = request.data.get('email', '')\n"
    "    for user in User.objects.filter(email=email):\n"
    "        uid = urlsafe_base64_encode(force_bytes(user.pk))\n"
    "        token = default_token_generator.make_token(user)\n"
    "        # TODO: send email with uid and token in production\n"
    "        return Response({'uid': uid, 'token': token})\n"
    "    return Response({'message': 'if the email exists a reset link has been sent'})\n\n\n"
    "@api_view(['POST'])\n"
    "@permission_classes([AllowAny])\n"
    "def reset_password(request):\n"
    "    try:\n"
    "        pk = force_str(urlsafe_base64_decode(request.data.get('uid', '')))\n"
    "        user = User.objects.get(pk=pk)\n"
    "    except (User.DoesNotExist, ValueError, TypeError):\n"
    "        return Response({'error': 'invalid link'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "    if not default_token_generator.check_token(user, request.data.get('token', '')):\n"
    "        return Response({'error': 'invalid or expired token'}, status=status.HTTP_400_BAD_REQUEST)\n"
    "    user.set_password(request.data.get('new_password', ''))\n"
    "    user.save()\n"
    "    return Response({'message': 'password reset successfully'})\n"
)

DJANGO_JWT_FBV_URL_CONFIG = (
    "from django.urls import path\n"
    "from rest_framework_simplejwt.views import TokenRefreshView\n"
    "from .views import register, login_view, logout_view, profile, forgot_password, reset_password\n\n"
    "urlpatterns = [\n"
    "    path('register/', register, name='register'),\n"
    "    path('login/', login_view, name='login'),\n"
    "    path('logout/', logout_view, name='logout'),\n"
    "    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),\n"
    "    path('profile/', profile, name='profile'),\n"
    "    path('forgot-password/', forgot_password, name='forgot-password'),\n"
    "    path('reset-password/', reset_password, name='reset-password'),\n"
    "]\n"
)

DJANGO_DOTENV_IMPORT = (
    "\nfrom dotenv import load_dotenv\n"
    "\nload_dotenv()\n"
)

DJANGO_DOTENV_ENV_EXAMPLE = (
    "\n# Django\n"
    "SECRET_KEY=your-secret-key-here\n"
    "DEBUG=True\n"
    "ALLOWED_HOSTS=localhost,127.0.0.1\n"
)

DJANGO_ENVIRON_SETUP = (
    "\nimport environ\n"
    "\nenv = environ.Env(\n"
    "    DEBUG=(bool, False),\n"
    ")\n"
    "environ.Env.read_env(BASE_DIR / '.env')\n"
)

DJANGO_ENVIRON_ENV_EXAMPLE = (
    "\n# Django\n"
    "SECRET_KEY=your-secret-key-here\n"
    "DEBUG=True\n"
    "ALLOWED_HOSTS=localhost,127.0.0.1\n"
)

DJANGO_CORS_SETTINGS = (
    "\n\n# django-cors-headers configuration\n"
    "CORS_ALLOW_CREDENTIALS = False\n"
    "CORS_ALLOWED_ORIGINS = [\n"
    "   'https://example.com',\n"
    "   'http://localhost:3000',\n"
    "]\n"
)