# ---------------------------------------------------------------------------
# Base project
# ---------------------------------------------------------------------------

FASTAPI_MAIN_PY = (
    "from fastapi import FastAPI\n"
    "from dotenv import load_dotenv\n"
    "# [BATTERY:IMPORTS]\n\n"
    "load_dotenv()\n\n"
    "app = FastAPI(\n"
    "    title=\"{project_name}\",\n"
    "    description=\"Generated by dev-scaffolder\",\n"
    "    version=\"0.1.0\",\n"
    ")\n\n"
    "# [BATTERY:MIDDLEWARE]\n\n"
    "\n@app.get(\"/\")\n"
    "async def root():\n"
    "    return {{\"message\": \"Hello World\"}}\n\n\n"
    "@app.get(\"/health\")\n"
    "async def health():\n"
    "    return {{\"status\": \"ok\"}}\n"
)

FASTAPI_REQUIREMENTS = (
    "fastapi\n"
    "uvicorn[standard]\n"
    "python-dotenv\n"
)

FASTAPI_ENV_EXAMPLE = (
    "# Application\n"
    "APP_ENV=development\n"
    "SECRET_KEY=change-me-in-production\n"
    "DEBUG=true\n"
)

# ---------------------------------------------------------------------------
# JWT Auth
# ---------------------------------------------------------------------------

FASTAPI_JWT_MAIN_PY = (
    "from fastapi import FastAPI\n"
    "from dotenv import load_dotenv\n"
    "from app.auth.router import router as auth_router\n"
    "# [BATTERY:IMPORTS]\n\n"
    "load_dotenv()\n\n"
    "app = FastAPI(\n"
    "    title=\"{project_name}\",\n"
    "    description=\"Generated by dev-scaffolder\",\n"
    "    version=\"0.1.0\",\n"
    ")\n\n"
    "# [BATTERY:MIDDLEWARE]\n\n"
    "app.include_router(auth_router, prefix=\"/auth\", tags=[\"auth\"])\n\n\n"
    "@app.get(\"/\")\n"
    "async def root():\n"
    "    return {{\"message\": \"Hello World\"}}\n\n\n"
    "@app.get(\"/health\")\n"
    "async def health():\n"
    "    return {{\"status\": \"ok\"}}\n"
)

FASTAPI_JWT_DATABASE_PY = (
    "from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine\n"
    "from sqlalchemy.orm import DeclarativeBase, sessionmaker\n"
    "import os\n\n"
    "DATABASE_URL = os.getenv(\"DATABASE_URL\", \"sqlite+aiosqlite:///./app.db\")\n\n"
    "engine = create_async_engine(DATABASE_URL, echo=False)\n"
    "AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)\n\n\n"
    "class Base(DeclarativeBase):\n"
    "    pass\n\n\n"
    "async def get_db():\n"
    "    async with AsyncSessionLocal() as session:\n"
    "        yield session\n"
)

FASTAPI_JWT_USER_MODEL_PY = (
    "from sqlalchemy import Integer, String, Boolean\n"
    "from sqlalchemy.orm import Mapped, mapped_column\n"
    "from app.database import Base\n\n\n"
    "class User(Base):\n"
    "    __tablename__ = \"users\"\n\n"
    "    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)\n"
    "    email: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)\n"
    "    username: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)\n"
    "    hashed_password: Mapped[str] = mapped_column(String, nullable=False)\n"
    "    is_active: Mapped[bool] = mapped_column(Boolean, default=True)\n"
)

FASTAPI_JWT_SCHEMAS_PY = (
    "from pydantic import BaseModel, EmailStr\n\n\n"
    "class UserCreate(BaseModel):\n"
    "    email: EmailStr\n"
    "    username: str\n"
    "    password: str\n\n\n"
    "class UserLogin(BaseModel):\n"
    "    email: EmailStr\n"
    "    password: str\n\n\n"
    "class UserResponse(BaseModel):\n"
    "    id: int\n"
    "    email: str\n"
    "    username: str\n"
    "    is_active: bool\n\n"
    "    model_config = {\"from_attributes\": True}\n\n\n"
    "class Token(BaseModel):\n"
    "    access_token: str\n"
    "    refresh_token: str\n"
    "    token_type: str = \"bearer\"\n\n\n"
    "class TokenRefresh(BaseModel):\n"
    "    refresh_token: str\n"
)

FASTAPI_JWT_UTILS_PY = (
    "from datetime import datetime, timedelta, timezone\n"
    "from passlib.context import CryptContext\n"
    "from jose import JWTError, jwt\n"
    "import os\n\n"
    "SECRET_KEY = os.getenv(\"SECRET_KEY\", \"change-me\")\n"
    "ALGORITHM = \"HS256\"\n"
    "ACCESS_TOKEN_EXPIRE_MINUTES = 30\n"
    "REFRESH_TOKEN_EXPIRE_DAYS = 7\n\n"
    "pwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\n\n\n"
    "def hash_password(password: str) -> str:\n"
    "    return pwd_context.hash(password)\n\n\n"
    "def verify_password(plain: str, hashed: str) -> bool:\n"
    "    return pwd_context.verify(plain, hashed)\n\n\n"
    "def create_access_token(data: dict) -> str:\n"
    "    expire = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)\n"
    "    return jwt.encode({**data, \"exp\": expire}, SECRET_KEY, algorithm=ALGORITHM)\n\n\n"
    "def create_refresh_token(data: dict) -> str:\n"
    "    expire = datetime.now(timezone.utc) + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)\n"
    "    return jwt.encode({**data, \"exp\": expire, \"type\": \"refresh\"}, SECRET_KEY, algorithm=ALGORITHM)\n\n\n"
    "def decode_token(token: str) -> dict:\n"
    "    return jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])\n"
)

FASTAPI_JWT_ROUTER_PY = (
    "from fastapi import APIRouter, Depends, HTTPException, status\n"
    "from sqlalchemy.ext.asyncio import AsyncSession\n"
    "from sqlalchemy import select\n"
    "from app.database import get_db\n"
    "from app.auth.models import User\n"
    "from app.auth.schemas import UserCreate, UserLogin, UserResponse, Token, TokenRefresh\n"
    "from app.auth.utils import hash_password, verify_password, create_access_token, create_refresh_token, decode_token\n\n"
    "router = APIRouter()\n\n\n"
    "@router.post(\"/register\", response_model=UserResponse, status_code=status.HTTP_201_CREATED)\n"
    "async def register(payload: UserCreate, db: AsyncSession = Depends(get_db)):\n"
    "    existing = await db.scalar(select(User).where(User.email == payload.email))\n"
    "    if existing:\n"
    "        raise HTTPException(status_code=400, detail=\"Email already registered\")\n"
    "    user = User(\n"
    "        email=payload.email,\n"
    "        username=payload.username,\n"
    "        hashed_password=hash_password(payload.password),\n"
    "    )\n"
    "    db.add(user)\n"
    "    await db.commit()\n"
    "    await db.refresh(user)\n"
    "    return user\n\n\n"
    "@router.post(\"/login\", response_model=Token)\n"
    "async def login(payload: UserLogin, db: AsyncSession = Depends(get_db)):\n"
    "    user = await db.scalar(select(User).where(User.email == payload.email))\n"
    "    if not user or not verify_password(payload.password, user.hashed_password):\n"
    "        raise HTTPException(status_code=401, detail=\"Invalid credentials\")\n"
    "    return Token(\n"
    "        access_token=create_access_token({\"sub\": str(user.id)}),\n"
    "        refresh_token=create_refresh_token({\"sub\": str(user.id)}),\n"
    "    )\n\n\n"
    "@router.post(\"/refresh\", response_model=Token)\n"
    "async def refresh(payload: TokenRefresh):\n"
    "    try:\n"
    "        data = decode_token(payload.refresh_token)\n"
    "        if data.get(\"type\") != \"refresh\":\n"
    "            raise HTTPException(status_code=401, detail=\"Invalid token type\")\n"
    "    except Exception:\n"
    "        raise HTTPException(status_code=401, detail=\"Invalid or expired token\")\n"
    "    return Token(\n"
    "        access_token=create_access_token({\"sub\": data[\"sub\"]}),\n"
    "        refresh_token=create_refresh_token({\"sub\": data[\"sub\"]}),\n"
    "    )\n\n\n"
    "@router.get(\"/me\", response_model=UserResponse)\n"
    "async def me(token: str, db: AsyncSession = Depends(get_db)):\n"
    "    try:\n"
    "        data = decode_token(token)\n"
    "    except Exception:\n"
    "        raise HTTPException(status_code=401, detail=\"Invalid or expired token\")\n"
    "    user = await db.get(User, int(data[\"sub\"]))\n"
    "    if not user:\n"
    "        raise HTTPException(status_code=404, detail=\"User not found\")\n"
    "    return user\n"
)

FASTAPI_JWT_ENV_EXAMPLE = (
    "# Application\n"
    "APP_ENV=development\n"
    "SECRET_KEY=change-me-in-production\n\n"
    "# Database\n"
    "DATABASE_URL=sqlite+aiosqlite:///./app.db\n"
    "# DATABASE_URL=postgresql+asyncpg://user:password@localhost/dbname\n"
)

FASTAPI_JWT_REQUIREMENTS = (
    "fastapi\n"
    "uvicorn[standard]\n"
    "python-dotenv\n"
    "sqlalchemy[asyncio]\n"
    "aiosqlite\n"
    "asyncpg\n"
    "alembic\n"
    "passlib[bcrypt]\n"
    "python-jose[cryptography]\n"
    "email-validator\n"
)

# ---------------------------------------------------------------------------
# Docker
# ---------------------------------------------------------------------------

FASTAPI_DOCKERFILE = (
    "FROM python:3.12-slim\n\n"
    "ENV PYTHONDONTWRITEBYTECODE=1 \\\n"
    "    PYTHONUNBUFFERED=1\n\n"
    "WORKDIR /app\n\n"
    "RUN apt-get update \\\n"
    "    && apt-get install -y --no-install-recommends gcc libpq-dev \\\n"
    "    && rm -rf /var/lib/apt/lists/*\n\n"
    "COPY requirements.txt .\n"
    "RUN pip install --no-cache-dir -r requirements.txt\n\n"
    "COPY . .\n\n"
    "EXPOSE 8000\n\n"
    "CMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
)

FASTAPI_DOCKER_COMPOSE = (
    "services:\n"
    "  web:\n"
    "    build: .\n"
    "    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload\n"
    "    volumes:\n"
    "      - .:/app\n"
    "    ports:\n"
    "      - \"8000:8000\"\n"
    "    env_file:\n"
    "      - .env\n"
    "    depends_on:\n"
    "      - db\n\n"
    "  db:\n"
    "    image: postgres:15\n"
    "    volumes:\n"
    "      - postgres_data:/var/lib/postgresql/data\n"
    "    environment:\n"
    "      POSTGRES_DB: ${POSTGRES_DB:-fastapi_db}\n"
    "      POSTGRES_USER: ${POSTGRES_USER:-fastapi_user}\n"
    "      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastapi_password}\n\n"
    "volumes:\n"
    "  postgres_data:\n"
)

FASTAPI_DOCKERIGNORE = (
    "__pycache__/\n"
    "*.py[cod]\n"
    "*.egg-info/\n"
    ".env\n"
    ".git/\n"
    ".venv/\n"
    "venv/\n"
    "dist/\n"
    "build/\n"
    "*.db\n"
    "*.log\n"
)

FASTAPI_DOCKER_ENV = (
    "# Application\n"
    "APP_ENV=development\n"
    "SECRET_KEY=change-me-in-production\n\n"
    "# PostgreSQL\n"
    "POSTGRES_DB=fastapi_db\n"
    "POSTGRES_USER=fastapi_user\n"
    "POSTGRES_PASSWORD=fastapi_password\n"
    "DATABASE_URL=postgresql+asyncpg://fastapi_user:fastapi_password@db:5432/fastapi_db\n"
)

# ---------------------------------------------------------------------------
# WebSockets
# ---------------------------------------------------------------------------

FASTAPI_WEBSOCKET_MAIN_PY = (
    "from fastapi import FastAPI, WebSocket, WebSocketDisconnect\n"
    "from dotenv import load_dotenv\n"
    "from typing import List\n"
    "# [BATTERY:IMPORTS]\n\n"
    "load_dotenv()\n\n"
    "app = FastAPI(\n"
    "    title=\"{project_name}\",\n"
    "    description=\"Generated by dev-scaffolder\",\n"
    "    version=\"0.1.0\",\n"
    ")\n\n"
    "# [BATTERY:MIDDLEWARE]\n\n\n"
    "class ConnectionManager:\n"
    "    def __init__(self):\n"
    "        self.active_connections: List[WebSocket] = []\n\n"
    "    async def connect(self, websocket: WebSocket):\n"
    "        await websocket.accept()\n"
    "        self.active_connections.append(websocket)\n\n"
    "    def disconnect(self, websocket: WebSocket):\n"
    "        self.active_connections.remove(websocket)\n\n"
    "    async def broadcast(self, message: str):\n"
    "        for connection in self.active_connections:\n"
    "            await connection.send_text(message)\n\n\n"
    "manager = ConnectionManager()\n\n\n"
    "@app.get(\"/\")\n"
    "async def root():\n"
    "    return {{\"message\": \"Hello World\"}}\n\n\n"
    "@app.get(\"/health\")\n"
    "async def health():\n"
    "    return {{\"status\": \"ok\"}}\n\n\n"
    "@app.websocket(\"/ws/{client_id}\")\n"
    "async def websocket_endpoint(websocket: WebSocket, client_id: str):\n"
    "    await manager.connect(websocket)\n"
    "    try:\n"
    "        while True:\n"
    "            data = await websocket.receive_text()\n"
    "            await manager.broadcast(f\"{{client_id}}: {{data}}\")\n"
    "    except WebSocketDisconnect:\n"
    "        manager.disconnect(websocket)\n"
    "        await manager.broadcast(f\"{{client_id}} disconnected\")\n"
)

# ---------------------------------------------------------------------------
# Batteries
# ---------------------------------------------------------------------------

FASTAPI_CORS_MIDDLEWARE_CODE = (
    "from fastapi.middleware.cors import CORSMiddleware\n"
)

FASTAPI_CORS_MIDDLEWARE_SETUP = (
    "app.add_middleware(\n"
    "    CORSMiddleware,\n"
    "    allow_origins=[\"http://localhost:3000\"],  # update for production\n"
    "    allow_credentials=True,\n"
    "    allow_methods=[\"*\"],\n"
    "    allow_headers=[\"*\"],\n"
    ")\n"
)

FASTAPI_SQLALCHEMY_DATABASE_PY = (
    "from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine\n"
    "from sqlalchemy.orm import DeclarativeBase, sessionmaker\n"
    "import os\n\n"
    "DATABASE_URL = os.getenv(\"DATABASE_URL\", \"sqlite+aiosqlite:///./app.db\")\n\n"
    "engine = create_async_engine(DATABASE_URL, echo=False)\n"
    "AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)\n\n\n"
    "class Base(DeclarativeBase):\n"
    "    pass\n\n\n"
    "async def get_db():\n"
    "    async with AsyncSessionLocal() as session:\n"
    "        yield session\n"
)

FASTAPI_SQLALCHEMY_IMPORTS = (
    "from app.database import get_db\n"
)

FASTAPI_TORTOISE_CONFIG_PY = (
    "import os\n\n"
    "TORTOISE_ORM = {\n"
    "    \"connections\": {\n"
    "        \"default\": os.getenv(\"DATABASE_URL\", \"sqlite://./app.db\"),\n"
    "    },\n"
    "    \"apps\": {\n"
    "        \"models\": {\n"
    "            \"models\": [\"app.models\", \"aerich.models\"],\n"
    "            \"default_connection\": \"default\",\n"
    "        },\n"
    "    },\n"
    "}\n"
)

FASTAPI_TORTOISE_MODELS_PY = (
    "from tortoise import fields\n"
    "from tortoise.models import Model\n\n\n"
    "class TimestampMixin:\n"
    "    created_at = fields.DatetimeField(auto_now_add=True)\n"
    "    updated_at = fields.DatetimeField(auto_now=True)\n\n\n"
    "class Item(Model, TimestampMixin):\n"
    "    id = fields.IntField(pk=True)\n"
    "    name = fields.CharField(max_length=255)\n"
    "    description = fields.TextField(null=True)\n\n"
    "    class Meta:\n"
    "        table = \"items\"\n"
)

FASTAPI_TORTOISE_REGISTER_CODE = (
    "from tortoise.contrib.fastapi import RegisterTortoise\n"
    "from app.tortoise_config import TORTOISE_ORM\n"
)

FASTAPI_TORTOISE_LIFESPAN = (
    "from contextlib import asynccontextmanager\n\n\n"
    "@asynccontextmanager\n"
    "async def lifespan(app):\n"
    "    async with RegisterTortoise(app=app, config=TORTOISE_ORM, generate_schemas=True):\n"
    "        yield\n\n"
)

FASTAPI_CELERY_APP_PY = (
    "from celery import Celery\n"
    "import os\n\n"
    "celery_app = Celery(\n"
    "    \"worker\",\n"
    "    broker=os.getenv(\"CELERY_BROKER_URL\", \"redis://localhost:6379/0\"),\n"
    "    backend=os.getenv(\"CELERY_RESULT_BACKEND\", \"redis://localhost:6379/0\"),\n"
    ")\n\n"
    "celery_app.conf.update(\n"
    "    task_serializer=\"json\",\n"
    "    result_serializer=\"json\",\n"
    "    accept_content=[\"json\"],\n"
    "    timezone=\"UTC\",\n"
    ")\n"
)

FASTAPI_CELERY_TASKS_PY = (
    "from app.celery_app import celery_app\n\n\n"
    "@celery_app.task\n"
    "def add(x, y):\n"
    "    return x + y\n\n\n"
    "@celery_app.task\n"
    "def sample_task():\n"
    "    # Replace with your task logic\n"
    "    return \"Task completed\"\n"
)

FASTAPI_PYTEST_CONFTEST_PY = (
    "import pytest\n"
    "from httpx import AsyncClient, ASGITransport\n"
    "from app.main import app\n\n\n"
    "@pytest.fixture\n"
    "async def client():\n"
    "    async with AsyncClient(transport=ASGITransport(app=app), base_url=\"http://test\") as c:\n"
    "        yield c\n"
)

FASTAPI_PYTEST_TEST_MAIN_PY = (
    "import pytest\n\n\n"
    "@pytest.mark.anyio\n"
    "async def test_root(client):\n"
    "    response = await client.get(\"/\")\n"
    "    assert response.status_code == 200\n\n\n"
    "@pytest.mark.anyio\n"
    "async def test_health(client):\n"
    "    response = await client.get(\"/health\")\n"
    "    assert response.status_code == 200\n"
)

FASTAPI_SENTRY_IMPORT = (
    "import sentry_sdk\n"
    "import os\n"
)

FASTAPI_SENTRY_SETUP = (
    "sentry_sdk.init(\n"
    "    dsn=os.getenv(\"SENTRY_DSN\", \"\"),  # set SENTRY_DSN in your environment\n"
    "    traces_sample_rate=1.0,\n"
    ")\n"
)

FASTAPI_STRUCTLOG_IMPORT = (
    "import structlog\n"
)

FASTAPI_STRUCTLOG_SETUP = (
    "structlog.configure(\n"
    "    processors=[\n"
    "        structlog.contextvars.merge_contextvars,\n"
    "        structlog.processors.add_log_level,\n"
    "        structlog.processors.TimeStamper(fmt=\"iso\"),\n"
    "        structlog.dev.ConsoleRenderer(),\n"
    "    ],\n"
    "    wrapper_class=structlog.BoundLogger,\n"
    "    context_class=dict,\n"
    "    logger_factory=structlog.PrintLoggerFactory(),\n"
    ")\n"
)
